[package]
name = "sam-rs"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "sam"
path = "src/bin/sam.rs"

[profile.release]
strip = true
lto = true
opt-level = "z"

[dependencies]
lazy_static = "1.4.0"
regex = "1.*"
thiserror = "1.0"