[package]
name = "sam-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sam"
path = "src/bin/sam.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "3.*", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.*"
thiserror = "1.0"